### ISSUE TITLE
Some JSON Dates Are One Month in the Future

### ISSUE THREAD

**Issue by bobmor99** [SignalK/signalk-multiplexer-node#7]
I'm not sure if this is a signalk-server-node, signalk-nmea0183, or a signalk-multiplexer-node issue.
```
bin/nmea-from-file
```
http://localhost:3000/api/v1/
shows some datestamps of 2015-03-24  and others with 2015-02-24  (today).
```
{"self":"10101010","version":1,"vessels":{"10101010":{"uuid":"10101010","navigation":{"speedThroughWater":{"value":3.1277777777777778,"source":{"type":"NMEA0183","src":"VHW","label":"signalk-parser-nmea0183"},"timestamp":"2015-03-24T16:57:36.000Z"},"courseOverGroundMagnetic":{"value":210.48,"source":{"type":"NMEA0183","src":"VTG","label":"signalk-parser-nmea0183"},"timestamp":"2015-03-24T16:57:36.000Z"},"courseOverGroundTrue":{"value":210.48,"source":{"type":"NMEA0183","src":"VTG","label":"signalk-parser-nmea0183"},"timestamp":"2015-03-24T16:57:36.000Z"},"speedOverGround":{"value":2.9323340761912995,"source":{"type":"NMEA0183","src":"VTG","label":"signalk-parser-nmea0183"},"timestamp":"2015-03-24T16:57:36.000Z"},"position":{"source":{},"timestamp":"2015-02-24T16:57:36.815Z","longitude":23.535516666666666,"latitude":60.08206666666667}},"environment":{"wind":{"angleApparent":{"timestamp":"2015-03-24T16:57:35.000Z","source":{"type":"NMEA0183","src":"MWV","label":"signalk-parser-nmea0183"},"value":-17},"speedApparent":{"timestamp":"2015-03-24T16:57:35.000Z","source":{"type":"NMEA0183","src":"MWV","label":"signalk-parser-nmea0183"},"value":7.099335131831568},"source":{},"timestamp":"2015-02-24T16:57:36.415Z","angleTrue":{"timestamp":"2015-03-24T16:57:36.000Z","source":{"type":"NMEA0183","src":"MWV","label":"signalk-parser-nmea0183"},"value":-29},"speedTrue":{"timestamp":"2015-03-24T16:57:36.000Z","source":{"type":"NMEA0183","src":"MWV","label":"signalk-parser-nmea0183"},"value":4.357345548305317}},"depth":{"belowTransducer":{"source":{"type":"NMEA0183","src":"DBT","label":"signalk-parser-nmea0183"},"timestamp":"2015-03-24T16:57:36.000Z","value":7.1},"source":{},"timestamp":"2015-02-24T16:57:36.714Z"}}}}}
```

**Comment by fabdrol** [comment]
Good catch.. I'll investigate where it's coming from this weekend. Which data points feature the wrong dates?

**Comment by bobmor99** [comment]
I hoped I chopped this up properly.


{"self":"10101010","version":1,"vessels":{"10101010":{"uuid":"10101010","navigation":

======================================

{"speedThroughWater":{"value":3.1277777777777778,"source":{"type":"NMEA0183","src":"VHW","label":"signalk-parser-nmea0183"},"timestamp":"2015-03-24T16:57:36.000Z"},

======================================

"courseOverGroundMagnetic":{"value":210.48,"source":{"type":"NMEA0183","src":"VTG","label":"signalk-parser-nmea0183"},"timestamp":"2015-03-24T16:57:36.000Z"},

=======================================

"courseOverGroundTrue":{"value":210.48,"source":{"type":"NMEA0183","src":"VTG","label":"signalk-parser-nmea0183"},"timestamp":"2015-03-24T16:57:36.000Z"},

=======================================

"speedOverGround":{"value":2.9323340761912995,"source":{"type":"NMEA0183","src":"VTG","label":"signalk-parser-nmea0183"},"timestamp":"2015-03-24T16:57:36.000Z"},

==========================================

"position":{"source":{},"timestamp":"2015-02-24T16:57:36.815Z","longitude":23.535516666666666,"latitude":60.08206666666667}},"environment":{"wind":{"angleApparent":{"timestamp":"2015-03-24T16:57:35.000Z",

===========================================

"source":{"type":"NMEA0183","src":"MWV","label":"signalk-parser-nmea0183"},"value":-17},"speedApparent":{"timestamp":"2015-03-24T16:57:35.000Z",

============================================

"source":{"type":"NMEA0183","src":"MWV","label":"signalk-parser-nmea0183"},"value":7.099335131831568},"source":{},"timestamp":"2015-02-24T16:57:36.415Z","angleTrue":{"timestamp":"2015-03-24T16:57:36.000Z",

============================================

"source":{"type":"NMEA0183","src":"MWV","label":"signalk-parser-nmea0183"},"value":-29},"speedTrue":{"timestamp":"2015-03-24T16:57:36.000Z",

============================================

"source":{"type":"NMEA0183","src":"MWV","label":"signalk-parser-nmea0183"},"value":4.357345548305317}},"depth":{"belowTransducer":{"source":{"type":"NMEA0183","src":"DBT","label":"signalk-parser-nmea0183"},"timestamp":"2015-03-24T16:57:36.000Z",

============================================

"value":7.1},"source":{},"timestamp":"2015-02-24T16:57:36.714Z"}}}}}

On Tue, Feb 24, 2015 at 12:17 PM, Fabian Tollenaar <notifications@github.com

**Comment by bobmor99** [comment]
This was fixed with resolution of: https://github.com/SignalK/signalk-parser-nmea0183/issues/25
